### ISSUE TITLE
Set a default Authorization

### ISSUE THREAD

**Issue by dzung1nguyen** [revolsys/kong-plugin-upstream-auth-basic#1]
Hi guy,

We can set a default Authorization Basic?

My issue:

Client call api_url  -> KONG -> upstream_url

Step 1-  Client call api_url  -> KONG: i use JWT plugin to check

Step 2- KONG -> upstream_url: set a define key:secret (username:password)

Please help me clear.

I am using Kong 0.10.0

Thank so much.

**Comment by dzung1nguyen** [comment]
The plugin Request Transform help me do that.

Thank you.

**Comment by pauldaustin** [comment]
Yes this plugin allows you to set the HTTP Basic Authorization header on the upstream to a single fixed username and password.

See the README for how to install this plugin into kong and the parameters for the plugin. See the kong documentation for general kong plugin documentation.

As you mentioned the Request Transform could also be used.
