### ISSUE TITLE
Announce plugin on mailing list

### ISSUE THREAD

**Issue by thibaultcha** [revolsys/kong-plugin-upstream-auth-basic#2]
Hello!

Good job on the plugin! We are happy to see members of the community stepping forward and publishing Kong plugins on Luarocks :)

As of now, we don't offer you yet a way to advertise your plugin on https://getkong.org/plugins, but are planning to in the future. In the meantime, feel free to publish an announcement on the [Kong Mailing List](https://groups.google.com/forum/#!forum/konglayer), as I am sure it will give you some exposition and peak the interest some of the Kong users out there (in fact, I have personally seen several requests for such a plugin last few days).

```
[ANN] Community Plugin - upstream-auth 1.0.1
```

Just a suggestion :)

Best,
Thibault

**Comment by pauldaustin** [comment]
Thibault,

Thanks for the suggestion. I've published an announcement on the mailing list

**Comment by thibaultcha** [comment]
Great! Don't hesitate to announce your updates on there in the future as well :)

Cheers,
Thibault
